name: BilibiliBind
version: '${project.version}'
main: cn.paper_card.bilibili_bind.ThePlugin
api-version: '1.20'
author: Paper99
folia-supported: true

depend:
  - Database

commands:
  bili-bind:
    permission: bili-bind.command

permissions:
  bili-bind.command:
    default: op
